module.exports = {

mathematicsAndNaturalSciences : [
    { code: '', title: 'МАТЕМАТИКА И МЕХАНИКА', degree: '', exams: '', professions: '', classes: '', description: '' },
    { code: '01.03.01', title: 'Математика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '01.03.02', title: 'Прикладная математика и информатика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '01.03.03', title: 'Механика и математическое моделирование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '01.03.04', title: 'Прикладная математика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '01.03.05', title: 'Статистика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '', title: 'КОМПЬЮТЕРНЫЕ И ИНФОРМАЦИОННЫЕ НАУКИ', degree: '', exams: '', professions: '', classes: '', description: ''  },
    { code: '02.03.01', title: 'Математика и компьютерные науки', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '02.03.02', title: 'Фундаментальная информатика и информационные технологии', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '02.03.03', title: 'Математическое обеспечение и администрирование информационных систем', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '', title: 'ФИЗИКА И АСТРОНОМИЯ', degree: '', exams: '', professions: '', classes: '', description: ''  },
    { code: '03.03.01', title: 'Прикладные математика и физика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '03.03.02', title: 'Физика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '03.03.03', title: 'Радиофизика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '', title: 'ХИМИЯ', degree: '' },
    { code: '04.03.01', title: 'Химия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '04.03.02', title: 'Химия, физика и механика материалов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '', title: 'НАУКИ О ЗЕМЛЕ', degree: '', exams: '', professions: '', classes: '', description: ''  },
    { code: '05.03.01', title: 'Геология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '05.03.02', title: 'География', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '05.03.03', title: 'Картография и геоинформатика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '05.03.04', title: 'Гидрометеорология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '05.03.04', title: 'Прикладная гидрометеорология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '05.03.05', title: 'Экология и природопользование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '', title: 'БИОЛОГИЧЕСКИЕ НАУКИ', degree: '', exams: '', professions: '', classes: '', description: ''  },
    { code: '06.03.01', title: 'Биология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '06.03.02', title: 'Почвоведение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  }
],

 engineeringTechnologyAndTechnicalSciences : [
        { code: '07.03.01', title: 'Архитектура', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '07.03.02', title: 'Реконструкция и реставрация архитектурного наследия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '07.03.03', title: 'Дизайн архитектурной среды', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '07.03.04', title: 'Градостроительство', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ТЕХНИКА И ТЕХНОЛОГИИ СТРОИТЕЛЬСТВА', degree: '' },
        { code: '08.03.01', title: 'Строительство', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ИНФОРМАТИКА И ВЫЧИСЛИТЕЛЬНАЯ ТЕХНИКА', degree: '' },
        { code: '09.03.01', title: 'Информатика и вычислительная техника', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '09.03.02', title: 'Информационные системы и технологии', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '09.03.03', title: 'Прикладная информатика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '09.03.04', title: 'Программная инженерия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ИНФОРМАЦИОННАЯ БЕЗОПАСНОСТЬ', degree: '' },
        { code: '10.03.01', title: 'Информационная безопасность', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ЭЛЕКТРОНИКА, РАДИОТЕХНИКА И СИСТЕМЫ СВЯЗИ', degree: '' },
        { code: '11.03.01', title: 'Радиотехника', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '11.03.02', title: 'Инфокоммуникационные технологии и системы связи', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '11.03.03', title: 'Конструирование и технология электронных средств', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '11.03.04', title: 'Электроника и наноэлектроника', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ФОТОНИКА, ПРИБОРОСТРОЕНИЕ, ОПТИЧЕСКИЕ И БИОТЕХНИЧЕСКИЕ СИСТЕМЫ И ТЕХНОЛОГИИ', degree: '' },
        { code: '12.03.01', title: 'Приборостроение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '12.03.02', title: 'Оптотехника', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '12.03.03', title: 'Фотоника и оптоинформатика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '12.03.04', title: 'Биотехнические системы и технологии', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ЭЛЕКТРО - И ТЕПЛОЭНЕРГЕТИКА', degree: '' },
        { code: '13.03.01', title: 'Теплоэнергетика и теплотехника', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '13.03.02', title: 'Электроэнергетика и электротехника', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '13.03.03', title: 'Энергетическое машиностроение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ЯДЕРНАЯ ЭНЕРГЕТИКА И ТЕХНОЛОГИИ', degree: '' },
        { code: '14.03.01', title: 'Ядерная энергетика и теплофизика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '14.03.02', title: 'Ядерные физика и технологии', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'МАШИНОСТРОЕНИЕ', degree: '' },
        { code: '15.03.01', title: 'Машиностроение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '15.03.02', title: 'Технологические машины и оборудование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '15.03.03', title: 'Прикладная механика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '15.03.04', title: 'Автоматизация технологических процессов и производств', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '15.03.05', title: 'Конструкторско-технологическое обеспечение машиностроительных производств', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '15.03.06', title: 'Мехатроника и робототехника', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ФИЗИКО-ТЕХНИЧЕСКИЕ НАУКИ И ТЕХНОЛОГИИ', degree: '' },
        { code: '16.03.01', title: 'Техническая физика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '16.03.02', title: 'Высокотехнологические плазменные и энергетические установки', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '16.03.03', title: 'Холодильная, криогенная техника и системы жизнеобеспечения', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ОРУЖИЕ И СИСТЕМЫ ВООРУЖЕНИЯ', degree: '' },
        { code: '17.03.01', title: 'Корабельное вооружение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ХИМИЧЕСКИЕ ТЕХНОЛОГИИ', degree: '' },
        { code: '18.03.01', title: 'Химическая технология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '18.03.02', title: 'Энерго- и ресурсосберегающие процессы в химической технологии, нефтехимии и биотехнологии', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ПРОМЫШЛЕННАЯ ЭКОЛОГИЯ И БИОТЕХНОЛОГИИ', degree: '' },
        { code: '19.03.01', title: 'Биотехнология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '19.03.02', title: 'Продукты питания из растительного сырья', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '19.03.03', title: 'Продукты питания животного происхождения', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '19.03.04', title: 'Технология продукции и организация общественного питания', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ТЕХНОСФЕРНАЯ БЕЗОПАСНОСТЬ И ПРИРОДООБУСТРОЙСТВО', degree: '' },
        { code: '20.03.01', title: 'Техносферная безопасность', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '20.03.02', title: 'Природообустройство и водопользование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ПРИКЛАДНАЯ ГЕОЛОГИЯ, ГОРНОЕ ДЕЛО, НЕФТЕГАЗОВОЕ ДЕЛО И ГЕОДЕЗИЯ', degree: '' },
        { code: '21.03.01', title: 'Нефтегазовое дело', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '21.03.02', title: 'Землеустройство и кадастры', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '21.03.03', title: 'Геодезия и дистанционное зондирование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ТЕХНОЛОГИИ МАТЕРИАЛОВ', degree: '' },
        { code: '22.03.01', title: 'Материаловедение и технологии материалов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '22.03.02', title: 'Металлургия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ТЕХНИКА И ТЕХНОЛОГИИ НАЗЕМНОГО ТРАНСПОРТА', degree: '' },
        { code: '23.03.01', title: 'Технология транспортных процессов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '23.03.02', title: 'Наземные транспортно-технологические комплексы', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '23.03.03', title: 'Эксплуатация транспортно-технологических машин и комплексов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'АВИАЦИОННАЯ И РАКЕТНО-КОСМИЧЕСКАЯ ТЕХНИКА', degree: '' },
        { code: '24.03.01', title: 'Ракетные комплексы и космонавтика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '24.03.02', title: 'Системы управления движением и навигация', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '24.03.03', title: 'Баллистика и гидроаэродинамика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '24.03.04', title: 'Авиастроение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '24.03.05', title: 'Двигатели летательных аппаратов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'АЭРОНАВИГАЦИЯ И ЭКСПЛУАТАЦИЯ АВИАЦИОННОЙ И РАКЕТНО-КОСМИЧЕСКОЙ ТЕХНИКИ', degree: '' },
        { code: '25.03.01', title: 'Техническая эксплуатация летательных аппаратов и двигателей', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '25.03.02', title: 'Техническая эксплуатация авиационных электросистем и пилотажно-навигационных комплексов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '25.03.03', title: 'Аэронавигация', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '25.03.04', title: 'Эксплуатация аэропортов и обеспечение полетов воздушных судов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ТЕХНИКА И ТЕХНОЛОГИИ КОРАБЛЕСТРОЕНИЯ И ВОДНОГО ТРАНСПОРТА ', degree: '' },
        { code: '26.03.01', title: 'Управление водным транспортом и гидрографическое обеспечение судоходства', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '26.03.02', title: 'Кораблестроение, океанотехника и системотехника объектов морской инфраструктуры', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '26.03.03', title: 'Водные пути, порты и гидротехнические сооружения', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '26.03.04', title: 'Инженерно-экономическое обеспечение технологий и бизнес-процессов водного транспорта', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'УПРАВЛЕНИЕ В ТЕХНИЧЕСКИХ СИСТЕМАХ', degree: '' },
        { code: '27.03.01', title: 'Стандартизация и метрология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '27.03.02', title: 'Управление качеством', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '27.03.03', title: 'Системный анализ и управление', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '27.03.04', title: 'Управление в технических системах', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '27.03.05', title: 'Инноватика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'НАНОТЕХНОЛОГИИ И НАНОМАТЕРИАЛЫ ', degree: '' },
        { code: '28.03.01 ', title: 'Нанотехнологии и микросистемная техника ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '28.03.02 ', title: 'Наноинженерия ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '28.03.03 ', title: 'Наноматериалы ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '', title: 'ТЕХНОЛОГИИ ЛЕГКОЙ ПРОМЫШЛЕННОСТИ', degree: '' },
        { code: '29.03.01', title: 'Технология изделий легкой промышленности', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '29.03.02', title: 'Технологии и проектирование текстильных изделий', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '29.03.03', title: 'Технология полиграфического и упаковочного производства', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '29.03.04', title: 'Технология художественной обработки материалов', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
        { code: '29.03.05', title: 'Конструирование изделий легкой промышленности', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  }
],
healthcareAndMedicalSciences :  [
     { code: '', title: 'СЕСТРИНСКОЕ ДЕЛО', degree: '' },
      { code: '34.03.01', title: 'Сестринское дело', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  }
] ,

 agricultureAndAgriculturalSciences : [
    { code: '', title: 'СЕЛЬСКОЕ, ЛЕСНОЕ И РЫБНОЕ ХОЗЯЙСТВО', degree: '' },
      { code: '35.03.01', title: 'Лесное дело', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.02', title: 'Технология лесозаготовительных и деревоперерабатывающих производств', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.03', title: 'Агрохимия и агропочвоведение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.04', title: 'Агрономия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.05', title: 'Садоводство', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.06', title: 'Агроинженерия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.07', title: 'Технология производства и переработки сельскохозяйственной продукции', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.08', title: 'Водные биоресурсы и аквакультура', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.09', title: 'Промышленное рыболовство', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.10', title: 'Ландшафтная архитектура', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '35.03.11', title: 'Гидромелиорация', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ВЕТЕРИНАРИЯ И ЗООТЕХНИЯ ', degree: '' },
      { code: '36.03.01 ', title: 'Ветеринарно-санитарная экспертиза ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '36.03.02 ', title: 'Зоотехния ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  }
],

 socialSciences : [
    { code: '', title: 'ПСИХОЛОГИЧЕСКИЕ НАУКИ', degree: '' },
      { code: '37.03.01', title: 'Психология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '37.03.02', title: 'Конфликтология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ЭКОНОМИКА И УПРАВЛЕНИЕ ', degree: '' },
      { code: '38.03.01 ', title: 'Экономика ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '38.03.02 ', title: 'Менеджмент ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '38.03.03 ', title: 'Управление персоналом ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '38.03.04 ', title: 'Государственное и муниципальное управление ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '38.03.05 ', title: 'Бизнес-информатика ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '38.03.06 ', title: 'Торговое дело ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '38.03.07 ', title: 'Товароведение ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '38.03.10 ', title: 'Жилищное хозяйство и коммунальная инфраструктура ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'СОЦИОЛОГИЯ И СОЦИАЛЬНАЯ РАБОТА', degree: '' },
      { code: '39.03.01', title: 'Социология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '39.03.02', title: 'Социальная работа', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '39.03.03', title: 'Организация работы с молодежью', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ЮРИСПРУДЕНЦИЯ', degree: '' },
      { code: '40.03.01', title: 'Юриспруденция', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '40.03.02', title: 'Обеспечение законности и правопорядка', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ПОЛИТИЧЕСКИЕ НАУКИ И РЕГИОНОВЕДЕНИЕ', degree: '' },
      { code: '41.03.01', title: 'Зарубежное регионоведение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '41.03.02', title: 'Регионоведение России', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '41.03.03 (1)', title: 'Востоковедение и африканистика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '41.03.04', title: 'Политология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '41.03.05', title: 'Международные отношения', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '41.03.06', title: 'Публичная политика и социальные науки', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'СРЕДСТВА МАССОВОЙ ИНФОРМАЦИИ И ИНФОРМАЦИОННО-БИБЛИОТЕЧНОЕ ДЕЛО', degree: '' },
      { code: '42.03.01', title: 'Реклама и связи с общественностью', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '42.03.02', title: 'Журналистика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '42.03.03', title: 'Издательское дело', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '42.03.04', title: 'Телевидение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '42.03.05', title: 'Медиакоммуникации', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'СЕРВИС И ТУРИЗМ', degree: '' },
      { code: '43.03.01', title: 'Сервис', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '43.03.02', title: 'Туризм', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '43.03.03', title: 'Гостиничное дело', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  }
],

 educationAndPedagogicalSciences : [
    { code: '44.03.01', title: 'Педагогическое образование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '44.03.02', title: 'Психолого-педагогическое образование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '44.03.03', title: 'Специальное (дефектологическое) образование', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '44.03.04', title: 'Профессиональное обучение (по отраслям)', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
    { code: '44.03.05', title: 'Педагогическое образование (с двумя профилями подготовки)', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  }
],

humanities : [
    { code: '', title: 'ЯЗЫКОЗНАНИЕ И ЛИТЕРАТУРОВЕДЕНИЕ', degree: '' },
      { code: '45.03.01', title: 'Филология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '45.03.02', title: 'Лингвистика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '45.03.03', title: 'Фундаментальная и прикладная лингвистика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '45.03.04', title: 'Интеллектуальные системы в гуманитарной сфере', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ИСТОРИЯ И АРХЕОЛОГИЯ', degree: '' },
      { code: '46.03.01 ', title: 'История ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '46.03.02 ', title: 'Документоведение и архивоведение ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '46.03.03 ', title: 'Антропология и этнология ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '46.03.04 ', title: 'Археология ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ФИЛОСОФИЯ, ЭТИКА И РЕЛИГИОВЕДЕНИЕ', degree: '' },
      { code: '47.03.01', title: 'Философия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '47.03.02', title: 'Прикладная этика', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '47.03.03', title: 'Религиоведение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ТЕОЛОГИЯ', degree: '' },
      { code: '48.03.01', title: 'Теология', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'ФИЗИЧЕСКАЯ КУЛЬТУРА И СПОРТ', degree: '' },
      { code: '49.03.01', title: 'Физическая культура', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '49.03.02', title: 'Физическая культура для лиц с отклонениями в состоянии здоровья (адаптивная физическая культура)', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '49.03.03', title: 'Рекреация и спортивно-оздоровительный туризм', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '49.03.04', title: 'Спорт', degree: 'Тренер по виду спорта, преподаватель' }
],

artAndCulture : [
    { code: '', title: 'ИСКУССТВОЗНАНИЕ', degree: '' },
      { code: '50.03.01', title: 'Искусства и гуманитарные науки', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '50.03.02', title: 'Изящные искусства', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '50.03.03', title: 'История искусств', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '50.03.04', title: 'Теория и история искусств', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'КУЛЬТУРОВЕДЕНИЕ И СОЦИОКУЛЬТУРНЫЕ ПРОЕКТЫ', degree: '' },
      { code: '51.03.01 ', title: 'Культурология ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '51.03.02 ', title: 'Народная художественная культура ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '51.03.03 ', title: 'Социально-культурная деятельность ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '51.03.04 ', title: 'Музеология и охрана объектов культурного и природного наследия ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '51.03.05 ', title: 'Режиссура театрализованных представлений и праздников ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '51.03.06 ', title: 'Библиотечно-информационная деятельность ', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'СЦЕНИЧЕСКИЕ ИСКУССТВА И ЛИТЕРАТУРНОЕ ТВОРЧЕСТВО', degree: '' },
      { code: '52.03.01', title: 'Хореографическое искусство', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '52.03.02', title: 'Хореографическое исполнительство', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '52.03.03', title: 'Цирковое искусство', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '52.03.04', title: 'Технология художественного оформления спектакля', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '52.03.05', title: 'Театроведение', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '52.03.06', title: 'Драматургия', degree: 'Бакалавр', exams: '', professions: '', classes: '', description: ''  },
      { code: '', title: 'МУЗЫКАЛЬНОЕ ИСКУССТВО', degree: '' },
      { code: '53.03.01', title: 'Музыкальное искусство эстрады', degree: 'Концертный исполнитель, артист ансамбля, преподаватель (инструменты эстрадного оркестра, эстрадно-джазовое пение, мюзикл, шоу-программы)' },
      { code: '53.03.02', title: 'Музыкально-инструментальное искусство', degree: 'Артист ансамбля, концертмейстер, преподаватель (фортепиано, орган, ааян, аккордеон и струнные щипковые инструменты ), артист оркестра, руководитель творческого коллектива (оркестровые духовые и ударные инструменты, струнные инструменты, национальные инструменты народов России )' },
      { code: '53.03.03', title: 'Вокальное искусство', degree: 'Концертно-камерный певец, преподаватель (академическое пение, театр оперетты), артист музыкального театра' },
      { code: '53.03.04', title: 'Искусство народного пения', degree: 'Хормейстер, руководитель творческого коллектива, преподаватель (хоровое народное пение, сольное народное пение), концертный исполнитель, солист ансамбля' },
      { code: '53.03.05', title: 'Дирижирование', degree: 'Дирижер хора, оркестра народных инструментов, оркестра духовых инструментов, оперно-симфонического оркестра, хормейстер, артист хора, преподаватель (дирижирование академическим хором, оркестром народных инструментов, оркестром духовых инструментов, оперно-симфоническим оркестром, певческое хоровое искусство)' },
      { code: '53.03.06', title: 'Музыкознание и музыкально-прикладное искусство', degree: 'Музыковед, лектор (музыковедение), музыкальный журналист, редактор СМИ (музыкальная журналистика и редакторская деятельность в СМИ), этномузыколог, руководитель творческого коллектива (этномузыкология, древнерусское певческое искусство), медиевист, преподаватель (музыкальная педагогика), аранжировщик (компьютерная музыка и аранжировка), менеджер музыкального искусства (менеджмент музыкального искусства), специалист в области музыкальной рекламы (музыкальная реклама)' }
]
};

